### ISSUE TITLE
Specific user's Conda setup is in remote_script.sh

### ISSUE THREAD

**Issue by edbennett** [sa2c/sunpyter#3]
[This line of remote_script.sh](https://github.com/sa2c/sunpyter/blob/5dbb0277deb8a581a9d5479217a309bcf24e849d/remote_script.sh#L13) has a specific reference to @TummyPan's environment. This should be removed.

**Comment by Tiany1Pan** [comment]
The path to my conda env has been removed.

**Comment by edbennett** [comment]
The comment "Please specify your own customised conda environment if you need." is not correct—either the default value should be one that works and gives a basic Jupyter notebook, or the comment should be adjusted such that setting this value correctly is required.

I prefer the former option; I'll update.

**Comment by edbennett** [comment]
Turns out the former option doesn't work because Jupyter needs to write to a subdirectory of the environment it is running from. There are hacky workarounds (E.g. create a thin wrapper of the base environment), but nothing elegant and it would be time consuming to implement, so I'll fall back to the second option above.
